alias k='kubectl'
alias olxpd='export AWS_PROFILE=olx-pk-dev'
alias olxps='export AWS_PROFILE=olx-pk-stage'
alias olxpp='export AWS_PROFILE=olx-pk-prod'
alias chamberd='AWS_PROFILE=olx-pk-dev chamber'
alias chambers='AWS_PROFILE=olx-pk-stage chamber'
alias chamberp='AWS_PROFILE=olx-pk-prod chamber'
alias olxbd='sshuttle --verbose --dns -NHr bastion-dev 10.0.0.0/12'
alias olxbs='sshuttle --verbose --dns -NHr bastion-stage 10.10.0.0/12'
alias olxbp='sshuttle --verbose --dns -NHr bastion-prod 10.20.0.0/12'
alias olxkd='kubectl config use-context olx-pk-development --namespace olx-pk-development'
alias olxks='kubectl config use-context olx-pk-staging --namespace olx-pk-staging'
alias olxkp='kubectl config use-context olx-pk-production --namespace olx-pk-live'
alias olxdbo='psql $(chamberp export ovation-olx-pk-production -f json | jq -r .DATABASE_URL)'
alias olxdb='psql $(chamberp export olx-pk-production -f json | jq -r .DATABASE_URL)'
alias olxdbr='psql $(chamberp export olx-pk-production -f json | jq -r .DATABASE_READ_REPLICA_URL)'
alias olxdbs='psql $(chambers export olx-pk-staging -f json | jq -r .DATABASE_URL)'