alias tf='terraform'
alias tfpd='terraform plan -out=default.tfplan'
alias tfad='terraform apply default.tfplan'
alias tfsd='tf-summarize default.tfplan'
alias tfi='terraform init'


alias dbbl='db BAYUT_LIVE'
alias dbbs='db BAYUT_STAGING'
alias dbbd='db BAYUT_DEVELOPMENT'
alias dbsal='db BAYUT_SA_LIVE'
alias dbsas='db BAYUT_SA_STAGING'
alias dbsad='db BAYUT_SA_DEVELOPMENT'
alias dbjol='db BAYUT_JO_LIVE'
alias dbjos='db BAYUT_JO_STAGING'
alias dbjod='db BAYUT_JO_DEVELOPMENT'
alias dbzl='db ZAMEEN_LIVE'
alias dbzs='db ZAMEEN_STAGING'
alias dbzd='db ZAMEEN_DEVELOPMENT'
